name: Build Password Generator

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    container: alpine:3.19
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install all dependencies
      run: |
        apk add --no-cache python3 py3-pip tk tk-dev binutils
        python3 -m venv /venv
        . /venv/bin/activate
        pip install --upgrade pip
        pip install pyinstaller
    
    - name: Build
      run: |
        . /venv/bin/activate
        pyinstaller --onefile --name password-generator password_generator.py
    
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: password-generator
        path: dist/password-generator
